/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注册新账号
         * @description 首次注册，返回 access + refresh token 并在服务端存 refresh token 哈希
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        /** @description 用于多端独立 refresh token */
                        deviceId: string;
                        displayName?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResult"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录
         * @description 同端重复登录会撤销旧 refresh token 并签发新的（rotation）
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        deviceId: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResult"];
                    };
                };
                /** @description Invalid credentials (不区分邮箱/密码错误，避免账号枚举) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新 access token
         * @description 用 refresh token 换取新 access + refresh（rotation：旧 refresh 立即撤销）
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                        deviceId: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（撤销当前端 refresh token） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                        deviceId: string;
                    };
                };
            };
            responses: {
                /** @description No Content（幂等：找不到/已撤销也返回 204） */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户资料 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicUser"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 更新用户资料
         * @description 部分更新 —— 体重 weightKg 用于卡路里计算
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        displayName?: string;
                        heightCm?: number;
                        weightKg?: number;
                        /** Format: date-time */
                        birthDate?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicUser"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/api/exercises/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出所有运动类型（含 MET + 注意事项） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            types?: components["schemas"]["ExerciseType"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询运动记录 */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            records?: components["schemas"]["ExerciseRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 创建运动记录
         * @description calories 由服务端按 MET 公式权威计算（**不接受客户端传入 calories**）
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example running */
                        typeId: string;
                        /** Format: date-time */
                        startedAt: string;
                        durationSec: number;
                        distanceKm?: number;
                        /** @description 幂等键（避免重复上报） */
                        clientId?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExerciseRecord"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上报每日步数
         * @description 同日多次上报采用 **max-value 策略**（避免移动端 OS 回退）
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @description 默认今天
                         */
                        date?: string;
                        steps: number;
                        /** @enum {string} */
                        source?: "ios_pedometer" | "android_sensor" | "manual";
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailyStep"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/steps/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询今日步数 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailyStep"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diet/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 搜索食物营养库 */
        get: {
            parameters: {
                query?: {
                    /** @description 匹配 nameZh 或 name */
                    q?: string;
                    category?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            foods?: components["schemas"]["Food"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diet/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询某时间段的饮食记录 */
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            records?: components["schemas"]["DietRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 记录一餐
         * @description 服务端计算 consumed = servings × servingSizeG/100 × per100g
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        foodId: number;
                        /** @enum {string} */
                        mealType: "breakfast" | "lunch" | "dinner" | "snack";
                        /** Format: date-time */
                        consumedAt?: string;
                        servings: number;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DietRecord"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diet/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询某日营养汇总 */
        get: {
            parameters: {
                query?: {
                    /** @description 默认今天 */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailyNutritionSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询情绪记录 */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            records?: components["schemas"]["MoodRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 记录一次情绪 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        mood: "happy" | "calm" | "sad" | "anxious" | "angry" | "tired" | "grateful" | "excited";
                        score?: number;
                        note?: string;
                        /** Format: date-time */
                        recordedAt?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MoodRecord"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mood/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询情绪趋势（按日聚合） */
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            trend?: components["schemas"]["MoodTrendPoint"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 发送 AI 对话
         * @description AI 回复带 **医疗免责声明**（你不是医生 / 不能替代专业诊断）。服务端未配置 ANTHROPIC_API_KEY / OPENAI_API_KEY 时返回 503 AI_DISABLED；上游 AI 失败时返回 502 AI_UPSTREAM_ERROR。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatSendResult"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description AI upstream error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description AI disabled (no API key configured) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询历史对话 */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            history?: components["schemas"]["ChatMessage"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example VALIDATION_ERROR */
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        PublicUser: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            displayName?: string | null;
            heightCm?: number | null;
            weightKg?: number | null;
            /** Format: date-time */
            birthDate?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        AuthResult: {
            user?: components["schemas"]["PublicUser"];
            accessToken?: string;
            refreshToken?: string;
        };
        ExerciseType: {
            /** @example running */
            id?: string;
            /** @example 跑步 */
            displayNameZh?: string;
            /** @example Running */
            displayNameEn?: string;
            /**
             * @description 代谢当量 MET，用于卡路里计算
             * @example 9.8
             */
            met?: number;
            /** @description 运动安全注意事项 */
            notes?: string;
        };
        ExerciseRecord: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            typeId?: string;
            /** Format: date-time */
            startedAt?: string;
            /** @example 1800 */
            durationSec?: number;
            distanceKm?: number | null;
            /** @description 服务端按 MET × weightKg × duration 计算 */
            calories?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        DailyStep: {
            userId?: string;
            /** @example 2026-08-12 */
            date?: string;
            /** @example 12000 */
            steps?: number;
            /** @enum {string|null} */
            source?: "ios_pedometer" | "android_sensor" | "manual" | null;
            /** Format: date-time */
            updatedAt?: string;
        };
        Food: {
            id?: number;
            name?: string;
            nameZh?: string | null;
            category?: string | null;
            servingSizeG?: number | null;
            kcalPer100g?: number | null;
            proteinG?: number | null;
            fatG?: number | null;
            carbsG?: number | null;
            fiberG?: number | null;
            sodiumMg?: number | null;
        };
        DietRecord: {
            /** Format: uuid */
            id?: string;
            userId?: string;
            foodId?: number;
            /** @enum {string} */
            mealType?: "breakfast" | "lunch" | "dinner" | "snack";
            /** Format: date-time */
            consumedAt?: string;
            servings?: number;
            food?: components["schemas"]["Food"];
            /** @description 服务端按 servings × servingSizeG/100 × per100g 计算 */
            consumed?: {
                kcal?: number;
                proteinG?: number;
                fatG?: number;
                carbsG?: number;
                fiberG?: number;
                sodiumMg?: number;
            };
        };
        DailyNutritionSummary: {
            /** @example 2026-08-12 */
            date?: string;
            kcal?: number;
            proteinG?: number;
            fatG?: number;
            carbsG?: number;
            fiberG?: number;
            sodiumMg?: number;
            recordCount?: number;
            byMeal?: {
                [key: string]: {
                    kcal?: number;
                    recordCount?: number;
                };
            };
        };
        MoodRecord: {
            id?: string;
            userId?: string;
            /** @enum {string} */
            mood?: "happy" | "calm" | "sad" | "anxious" | "angry" | "tired" | "grateful" | "excited";
            score?: number | null;
            note?: string | null;
            /** Format: date-time */
            recordedAt?: string;
        };
        MoodTrendPoint: {
            date?: string;
            avgScore?: number | null;
            recordCount?: number;
            dominantMood?: string;
        };
        ChatMessage: {
            id?: string;
            userId?: string;
            /** @enum {string} */
            role?: "user" | "assistant";
            content?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ChatSendResult: {
            userMessage?: components["schemas"]["ChatMessage"];
            assistantMessage?: components["schemas"]["ChatMessage"];
        };
    };
    responses: {
        /** @description Missing or invalid access token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Missing Authorization header"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request body or query failed Zod validation */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_ERROR",
                 *         "message": "Invalid request body",
                 *         "details": {
                 *           "fieldErrors": {},
                 *           "formErrors": []
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
